Repository Eccoar/2020.2-Eccoar_Gateway, pull requests merged in 2021-05, with the labels that each got.

#17 Solve #153 Retirada de denúncia
  src/api/complaint/ComplaintProxy.ts
  src/routes.ts
  test/Routes.test.ts
Labels: FEATURE, MDS

#28 HOTFIX Sonar .tests e Sonar .testExecutionReportPaths comentados
  sonar-project.properties
Labels: ANALYTICS, HOTFIX

#29 Solve #227 HOTFIX Sonar URL
  .gitlab-ci.yml
Labels: ANALYTICS, EPS, HOTFIX
