Repository Eccoar/2020.2-Eccoar_Gateway, pull requests merged in 2021-04, with the labels that each got.

#8 Solve #125 Detalhamento da denúncia
  src/api/complaint/ComplaintProxy.ts
  src/routes.ts
Labels: enhancement

#11 Solve #147 - Refatoração Gateway
  package-lock.json
  package.json
  src/api/complaint/ComplaintProxy.ts
  src/api/report/ReportProxy.ts
  src/api/users/UsersProxy.ts
  src/routes.ts
  src/server.ts
  test/ComplaintProxy.test.ts
  test/Routes.test.ts
Labels: FEATURE

#7 Solve #124 Envio de e-mails
  docker-compose.yml
  package-lock.json
  src/api/complaint/ComplaintProxy.ts
  src/api/mailer/MailerProxy.ts
  src/api/report/ReportProxy.ts
  src/config/enviroments.ts
  src/routes.ts
  test/Routes.test.ts
Labels: FEATURE

#18 Solve #138 Cadastro de usuário
  src/api/users/UsersProxy.ts
  src/routes.ts
  test/Routes.test.ts
Labels: FEATURE

#15 Solve #156 Configuração Sentry
  package.json
  src/api/complaint/ComplaintProxy.ts
  src/api/mailer/MailerProxy.ts
  src/api/report/ReportProxy.ts
  src/api/users/UsersProxy.ts
  src/config/sentry.ts
  src/server.ts
Labels: ANALYTICS, EASY, EPS
